Created Settings page, and add a new feature in profile
spe-uob/2021-ARReshare pull request #136
Opened 2022-03-21 17:55 UTC by Manoutofpower

- Created Settings page
- Finish most of the popups with icons
- Add a new feature in profile to clarify users

2022-03-28 16:08 UTC, artur-varosyan requested changes
Hi Ziqian, just a few change requests from me! Otherwise, it looks great! Profile and Settings pages look really intuitive

2022-03-28 16:08 UTC, artur-varosyan commented on app/src/main/res/layout/activity_profile.xml
> +                            android:text="Gained Products"
Can you please remove the gained section altogether please Ziqian?

2022-03-28 16:13 UTC, arfi2212 commented on app/src/main/java/com/example/ar_reshare/SettingActivity.java
> +                dialog2.setPositiveButton("Yes", new DialogInterface.OnClickListener() {
Could you please change "Yes" to "Confirm" for all the buttons?

2022-03-28 16:21 UTC, arfi2212 commented on app/src/main/java/com/example/ar_reshare/SettingActivity.java
> +                        Toast.makeText(v.getContext(), "New password:" + a, Toast.LENGTH_SHORT).show();
Could you please change the toast to just show "Your password has now been changed"? Instead of displaying the password back

2022-03-28 17:13 UTC, artur-varosyan approved these changes
Thank you for implementing the changes I requested Ziqian. It is ready to merge in my opinion.

2022-03-28 17:42 UTC, Lingtao-Cai approved these changes

2022-03-28 17:50 UTC, arfi2212 approved these changes
Thank you for making the changes we requested Ziqian. The page looks great :)

2022-03-29 12:42 UTC, HellinSun approved these changes
Great job thanks!

2022-03-29 12:43 UTC, Manoutofpower commented
Thx for everyone's comment! All of them fixed!

2022-03-29 12:44 UTC, merged